on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: my-variables-test-job
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    - name: Use variables
      run: |
        echo "github ref name: $REF_NAME"
        echo "repository variable : $MY_REPOSITORY_VARIABLE"
        echo "environment variable : $MY_TEST_VARIABLE"
        echo "variable from shell environment : $env_var"
      env:
        REF_NAME: ${{ github.ref_name }}
        MY_REPOSITORY_VARIABLE: ${{ vars.MY_REPOSITORY_VARIABLE }}
        MY_TEST_VARIABLE: ${{ vars.MY_TEST_VARIABLE }}
