on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  set-variables:
    name: my-variables-test-job
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    steps:
    - name: Split branch name
      env:
        BRANCH: ${{ github.ref_name }}
      id: split
      run: |
        if [[ "$BRANCH" == "main" ]]; then echo "fragment=prod"; else echo "fragment=${BRANCH##*_}"; fi >> $GITHUB_OUTPUT
    - name: Test variable
      run: |
        echo ${{steps.split.outputs.fragment}}
  display-variables:
    uses: ./.github/workflows/my_reusable_workflow.yaml
    needs: set-variables
    with:
      my-env: ${{ needs.set-variables.outputs.fragment }}
