on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  variables:
    name: my-variables-test-job
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    outputs:
      fragment: ${{ steps.split.outputs.fragment }}
    steps:
    - name: Split branch name
      env:
        BRANCH: ${{ github.ref_name }}
      id: split
      run: |
        if [[ "$BRANCH" == "main" ]]; then echo "fragment=prod"; else echo "fragment=${BRANCH##*_}"; fi >> $GITHUB_OUTPUT
  test-variables:
    name: Test variable job
    runs-on: ubuntu-latest
    needs: variables
    steps:
    - name: Test variable step
      run: |
        echo "${{ needs.variables.outputs.fragment }}"
  display-variables:
    uses: ./.github/workflows/my_reusable_workflow.yaml
    needs: variables
    with:
      my-env: ${{ needs.variables.outputs.fragment }}
